In [1]:
import importlib
import New_data_prep as dp

importlib.reload(dp)

In [4]:
VERSION = 'V1'
base_output_folder = "../experiments"
path_to_csvs = "../data/raw/source_domain/"
path_to_csvs_target = "../data/raw/target_domain/"
path_to_networks = "../data/networks"
n = 5
k = 4
seed = 4850
split_seed=42
PATH_TO_SPLITS =  f"../data/splits/{VERSION}/"
PATH_TO_SCALERS =  f'../output/scalers/baselines/{VERSION}/'
node_types = ["LIGHT", "MID", "HEAVY"]

In [5]:
#PATH_TO_AUGMENTED_ROWS = f"../data/augmented_rows/{VERSION}/"

In [6]:
simulation = 0

In [7]:
dp.prepare_data(
    base_output_folder,
    path_to_csvs,
    path_to_csvs_target,
    path_to_networks,
    PATH_TO_SPLITS,
    PATH_TO_SCALERS,
    n,
    k,
    seed,
    simulation,
    node_types,
    split_seed
)

/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/src/New_data_prep.py:59: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, *dataframes], axis=0, ignore_index=True)
/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/src/New_data_prep.py:70: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X.loc[:, col] = X.loc[:, col].fillna(0)

cpu_usage_function_shasum
23887
ram_usage_function_shasum
23430
medium_latency_function_shasum
23610
cpu_usage_function_curl
14017
ram_usage_function_curl
13650
medium_latency_function_curl
13920
cpu_usage_function_eat_memory
4571
ram_usage_function_eat_memory
4501
medium_latency_function_eat_memory
4564
cpu_usage_node
32741
ram_usage_node
32385
ram_usage_node_percentage
32127
ram_usage_node_perc_theor
32385
overloaded_node
overloaded_node
0.0    89169
1.0     9563
Name: count, dtype: int64
cpu_usage_function_nmap
7319
ram_usage_function_nmap
7245
medium_latency_function_nmap
7301
cpu_usage_function_env
19397
ram_usage_function_env
18812
medium_latency_function_env
19202
cpu_usage_function_figlet
19900
ram_usage_function_figlet
19762
medium_latency_function_figlet
19790
cpu_usage_function_figlet
16476
ram_usage_function_figlet
16403
medium_latency_function_figlet
16250
cpu_usage_function_shasum
16498
ram_usage_function_shasum
16352
medium_latency_function_shasum
16298
cpu_usage_function_nmap
7290
ram_usage_function_nmap
7192
medium_latency_function_nmap
7256
cpu_usage_node
21955
ram_usage_node
21629
ram_usage_node_percentage
22094
ram_usage_node_perc_theor
21629
overloaded_node
overloaded_node
0    59483
1     8090
Name: count, dtype: int64
cpu_usage_function_env
8297
ram_usage_function_env
8251
medium_latency_function_env
8119
cpu_usage_function_eat_memory
2817
ram_usage_function_eat_memory
2748
medium_latency_function_eat_memory
2756
cpu_usage_function_curl
6781
ram_usage_function_curl
6695
medium_latency_function_curl
6667
load nodes network
...done
build nodes dataframes
...done
split and save
processing node 0

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-06-09 15:02:27.116366
Start Train/Val Split: 2026-06-09 15:02:27.399765
Start Oversampling: 2026-06-09 15:02:27.517175

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 6340
After limiting: 2028 (removed 4312)

Class distribution after limiting:
overloaded_node
0.0                1870
1.0                 158
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 0] Overloaded: 158, Non-overloaded: 1870
Generating 1712 synthetic samples for node_type 0
Generated 1712 samples for node_type 0

 Total synthetic samples generated: 1712
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(0)]


--- Processing node_type: 0 ---
Original counts → overloaded=0: 5866, overloaded=1: 474
Need to add 5392 more rows for overloaded=1
Augmented rows available for this node_type=0: 1712
Repeating augmented rows 4 times
Rows actually added: 5392
After augmentation → overloaded=0: 5866, overloaded=1: 5866

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                5866
1.0                5866
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
0                5866  5866

Final node_type distribution:
node_type
0    11732
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 3740
Unique feature combinations for 0       : 1870
Unique feature combinations for 1       : 1870
==========================================

Start Preprocessing: 2026-06-09 15:02:27.598531

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
0          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        11732       1578        1980

## Data Leakage Check:

Train Samples: 11732
Val Samples: 1578
Test Samples: 1980


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (11732, 7)
  - Regression targets shape: (11732, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (11732, 7)
  - X_val shape: (1578, 7)
  - X_test shape: (1980, 7)

Transforming for Janoosy: 2026-06-09 15:02:27.651670
processing node 4

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-06-09 15:02:29.029198
Start Train/Val Split: 2026-06-09 15:02:29.285273
Start Oversampling: 2026-06-09 15:02:29.407198

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 6092
After limiting: 2028 (removed 4064)

Class distribution after limiting:
overloaded_node
0.0                1866
1.0                 162
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 0] Overloaded: 162, Non-overloaded: 1866
Generating 1704 synthetic samples for node_type 0
Generated 1704 samples for node_type 0

 Total synthetic samples generated: 1704
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(0)]


--- Processing node_type: 0 ---
Original counts → overloaded=0: 5606, overloaded=1: 486
Need to add 5120 more rows for overloaded=1
Augmented rows available for this node_type=0: 1704
Repeating augmented rows 4 times
Rows actually added: 5120
After augmentation → overloaded=0: 5606, overloaded=1: 5606

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                5606
1.0                5606
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node   0.0   1.0
node_type
0                5606  5606

Final node_type distribution:
node_type
0    11212
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 3732
Unique feature combinations for 0       : 1866
Unique feature combinations for 1       : 1866
==========================================

Start Preprocessing: 2026-06-09 15:02:29.482578

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
0          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        11212       1524        1903

## Data Leakage Check:

Train Samples: 11212
Val Samples: 1524
Test Samples: 1903


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (11212, 7)
  - Regression targets shape: (11212, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (11212, 7)
  - X_val shape: (1524, 7)
  - X_test shape: (1903, 7)

Transforming for Janoosy: 2026-06-09 15:02:29.550709
processing node 2

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-06-09 15:02:30.869439
Start Train/Val Split: 2026-06-09 15:02:31.628195
Start Oversampling: 2026-06-09 15:02:31.851500

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 18895
After limiting: 5817 (removed 13078)

Class distribution after limiting:
overloaded_node
0.0                5503
1.0                 314
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 1] Overloaded: 314, Non-overloaded: 5503
Generating 5189 synthetic samples for node_type 1
Generated 5189 samples for node_type 1

 Total synthetic samples generated: 5189
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(1)]


--- Processing node_type: 1 ---
Original counts → overloaded=0: 17915, overloaded=1: 980
Need to add 16935 more rows for overloaded=1
Augmented rows available for this node_type=1: 5189
Repeating augmented rows 4 times
Rows actually added: 16935
After augmentation → overloaded=0: 17915, overloaded=1: 17915

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                17915
1.0                17915
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node    0.0    1.0
node_type
1                17915  17915

Final node_type distribution:
node_type
1    35830
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 11006
Unique feature combinations for 0       : 5503
Unique feature combinations for 1       : 5503
==========================================

Start Preprocessing: 2026-06-09 15:02:32.061909

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
1          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        35830       4716        5878

## Data Leakage Check:

Train Samples: 35830
Val Samples: 4716
Test Samples: 5878


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (35830, 7)
  - Regression targets shape: (35830, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (35830, 7)
  - X_val shape: (4716, 7)
  - X_test shape: (5878, 7)

Transforming for Janoosy: 2026-06-09 15:02:32.191011
processing node 3

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-06-09 15:02:36.568186
Start Train/Val Split: 2026-06-09 15:02:37.317869
Start Oversampling: 2026-06-09 15:02:37.540301

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 17573
After limiting: 5817 (removed 11756)

Class distribution after limiting:
overloaded_node
0.0                5497
1.0                 320
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 1] Overloaded: 320, Non-overloaded: 5497
Generating 5177 synthetic samples for node_type 1
Generated 5177 samples for node_type 1

 Total synthetic samples generated: 5177
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(1)]


--- Processing node_type: 1 ---
Original counts → overloaded=0: 16616, overloaded=1: 957
Need to add 15659 more rows for overloaded=1
Augmented rows available for this node_type=1: 5177
Repeating augmented rows 4 times
Rows actually added: 15659
After augmentation → overloaded=0: 16616, overloaded=1: 16616

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                16616
1.0                16616
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node    0.0    1.0
node_type
1                16616  16616

Final node_type distribution:
node_type
1    33232
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 10994
Unique feature combinations for 0       : 5497
Unique feature combinations for 1       : 5497
==========================================

Start Preprocessing: 2026-06-09 15:02:37.734404

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
1          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        33232       4421        5499

## Data Leakage Check:

Train Samples: 33232
Val Samples: 4421
Test Samples: 5499


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (33232, 7)
  - Regression targets shape: (33232, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (33232, 7)
  - X_val shape: (4421, 7)
  - X_test shape: (5499, 7)

Transforming for Janoosy: 2026-06-09 15:02:37.850160
processing node 1

# Task: Multi_Task

---

Start CV Split (single fold only): 2026-06-09 15:02:41.779505
Start Train/Val Split: 2026-06-09 15:02:42.286449
Start Oversampling: 2026-06-09 15:02:42.452158

## Oversampling

=== Limiting to max 1 identical combinations ===
Original row count: 14321
After limiting: 3914 (removed 10407)

Class distribution after limiting:
overloaded_node
0.0                2917
1.0                 997
Name: count, dtype: int64

=== Generating synthetic overloaded samples (Unique Features Balancing) ===

[Node Type 2] Overloaded: 997, Non-overloaded: 2917
Generating 1920 synthetic samples for node_type 2
Generated 1920 samples for node_type 2

 Total synthetic samples generated: 1920
Augmented rows saved to 'augmented_overloaded_samples.csv'

========= ROWS BALANCING =========

Node types found: [np.int64(2)]


--- Processing node_type: 2 ---
Original counts → overloaded=0: 11081, overloaded=1: 3240
Need to add 7841 more rows for overloaded=1
Augmented rows available for this node_type=2: 1920
Repeating augmented rows 5 times
Rows actually added: 7841
After augmentation → overloaded=0: 11081, overloaded=1: 11081

========= BALANCING COMPLETED =========


Final class distribution after rebalancing:
overloaded_node
0.0                11081
1.0                11081
Name: count, dtype: int64

Final class distribution after rebalancing (node_type-wise):
overloaded_node    0.0    1.0
node_type
2                11081  11081

Final node_type distribution:
node_type
2    22162
Name: count, dtype: int64

========= FINAL UNIQUE FEATURES SUMMARY =========
Total unique feature combinations       : 5834
Unique feature combinations for 0       : 2917
Unique feature combinations for 1       : 2917
==========================================

Start Preprocessing: 2026-06-09 15:02:42.586015

## Preprocessing

# Multi_Task

---

## Node Type Distribution Across Splits:

           Train    Val   Test
node_type
2          100.0  100.0  100.0

 Dataset Sizes:
            Train Total  Val Total  Test Total
Total Rows        22162       3568        4435

## Data Leakage Check:

Train Samples: 22162
Val Samples: 3568
Test Samples: 4435


No data leakage detected. Splits are clean.

## Scalaing

[INFO] MinMaxScaler fitted:
  - Features shape: (22162, 7)
  - Regression targets shape: (22162, 3)
  - Classification column '['overloaded_node']' excluded from scaling

[INFO] Scalers saved for target 'Multi_Task'

[INFO] Transformation complete.
  - X_train shape: (22162, 7)
  - X_val shape: (3568, 7)
  - X_test shape: (4435, 7)

Transforming for Janoosy: 2026-06-09 15:02:42.688215
...done

'../experiments/5n-4k/seed4850/0'

In [8]:
import pandas as pd
import json
import os

folder = "/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/experiments/5n-4k/seed4850/0"

rows = []

for file in sorted(os.listdir(folder)):
    if file.endswith("_data.json") and file != "centralized_data.json":

        with open(os.path.join(folder, file)) as f:
            data = json.load(f)

        node_type = int(data["X_train"][0][0][-1])

        rows.append({
            "node": file.replace("_data.json", ""),
            "node_type": ["HEAVY", "MID", "LIGHT"][node_type]
        })

pd.DataFrame(rows)

  node node_type
0    0     HEAVY
1    1     LIGHT
2    2       MID
3    3       MID
4    4     HEAVY

# testing

In [78]:
import pandas as pd

In [79]:
df_augmentation=pd.read_csv('/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/data/augmented_rows/V1/augmented_overloaded_samples.csv')

In [80]:
df_augmentation.duplicated().sum()

np.int64(0)

In [81]:
df_augmentation[df_augmentation.duplicated()]

Empty DataFrame
Columns: [rate_function_curl, rate_function_eat_memory, rate_function_env, rate_function_figlet, rate_function_nmap, rate_function_shasum, node_type, overloaded_node, cpu_usage_node, ram_usage_node, ram_usage_node_percentage]
Index: []

In [82]:
df_augmentation.count()

rate_function_curl           1911
rate_function_eat_memory     1911
rate_function_env            1911
rate_function_figlet         1911
rate_function_nmap           1911
rate_function_shasum         1911
node_type                    1911
overloaded_node              1911
cpu_usage_node               1911
ram_usage_node               1911
ram_usage_node_percentage    1911
dtype: int64

In [83]:
import json

path = "/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/experiments/9n-8k/seed4850/0/8_data.json"

with open(path, "r") as f:
    data = json.load(f)

In [84]:
print(data.keys())

dict_keys(['X_train', 'Y_train', 'X_val', 'Y_val', 'X_test', 'Y_test'])

In [96]:
Y_train= data["Y_train"]

In [97]:
import numpy as np

Y_train = np.array(Y_train)

In [98]:
Y_flat = Y_train.reshape(Y_train.shape[0], -1)
df_Y = pd.DataFrame(Y_flat)

In [100]:
df_Y

             0         1         2    3
0     1.565072  1.235852  1.224230  0.0
1     1.515785  1.247027  1.229086  0.0
2     1.540481  1.243401  1.226580  0.0
3     1.583645  1.239013  1.220261  0.0
4     1.562825  1.229713  1.213577  0.0
...        ...       ...       ...  ...
2487  1.538328  1.564165  1.688982  1.0
2488  1.538328  1.564165  1.688982  1.0
2489  1.538328  1.564165  1.688982  1.0
2490  1.538328  1.564165  1.688982  1.0
2491  1.806737  1.764103  1.815300  1.0

[2492 rows x 4 columns]

In [85]:
X_train = data["X_train"]

In [86]:
X_train

[[[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.4500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.100000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.4500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.625, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.100000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.75, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.7999999523162842, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.2000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.4500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.5, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.7999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.100000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.125, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.100000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.4500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.25, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.0499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.100000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.600000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.850000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.9500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.375, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
 [[1.149999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.25, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.2999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.350000023841858, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.399999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.4500000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.5499999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.649999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7000000476837158, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.75, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.7999999523162842, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],
 [[1.899999976158142, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [1.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
  [1.850000023841858, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]],

In [87]:
import numpy as np

X_train = np.array(X_train)

In [88]:
X_flat = X_train.reshape(X_train.shape[0], -1)
df = pd.DataFrame(X_flat)

In [89]:
df

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1.60,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.250000,0.0,...,0.0,0.0,1.800,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.65,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.250000,0.0,...,0.0,0.0,1.800,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.70,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.250000,0.0,...,0.0,0.0,1.800,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.75,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.250000,0.0,...,0.0,0.0,1.800,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.80,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.250000,0.0,...,0.0,0.0,1.800,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2487,1.60,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.897436,0.0,...,0.0,0.0,1.950,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2488,1.60,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.948718,0.0,...,0.0,0.0,1.950,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2489,1.60,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.000000,0.0,...,0.0,0.0,1.950,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2490,1.60,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.102564,0.0,...,0.0,0.0,1.975,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2491,1.65,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.179487,0.0,...,0.0,0.0,1.950,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [90]:
df.duplicated().sum()

np.int64(0)

In [91]:
df.count()

0     2492
1     2492
2     2492
3     2492
4     2492
5     2492
6     2492
7     2492
8     2492
9     2492
10    2492
11    2492
12    2492
13    2492
14    2492
15    2492
16    2492
17    2492
18    2492
19    2492
20    2492
21    2492
22    2492
23    2492
dtype: int64

In [92]:
len(df.drop_duplicates())

2492

In [93]:
df[df.duplicated()]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Index: []

[0 rows x 24 columns]

In [94]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Index: []

[0 rows x 24 columns]

In [95]:
df.value_counts()[df.value_counts() > 2]

Series([], Name: count, dtype: int64)